# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.27.6/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.27.6/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/jisharajala/cactus/tests

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/jisharajala/cactus

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.27.6/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.27.6/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/jisharajala/cactus/CMakeFiles /Users/jisharajala/cactus//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/jisharajala/cactus/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named test_curl

# Build rule for target.
test_curl: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_curl
.PHONY : test_curl

# fast build rule for target.
test_curl/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_curl.dir/build.make CMakeFiles/test_curl.dir/build
.PHONY : test_curl/fast

#=============================================================================
# Target rules for targets named test_embed

# Build rule for target.
test_embed: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_embed
.PHONY : test_embed

# fast build rule for target.
test_embed/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_embed.dir/build.make CMakeFiles/test_embed.dir/build
.PHONY : test_embed/fast

#=============================================================================
# Target rules for targets named test_graph

# Build rule for target.
test_graph: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_graph
.PHONY : test_graph

# fast build rule for target.
test_graph/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_graph.dir/build.make CMakeFiles/test_graph.dir/build
.PHONY : test_graph/fast

#=============================================================================
# Target rules for targets named test_index

# Build rule for target.
test_index: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_index
.PHONY : test_index

# fast build rule for target.
test_index/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_index.dir/build.make CMakeFiles/test_index.dir/build
.PHONY : test_index/fast

#=============================================================================
# Target rules for targets named test_kernel

# Build rule for target.
test_kernel: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_kernel
.PHONY : test_kernel

# fast build rule for target.
test_kernel/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_kernel.dir/build.make CMakeFiles/test_kernel.dir/build
.PHONY : test_kernel/fast

#=============================================================================
# Target rules for targets named test_kv_cache

# Build rule for target.
test_kv_cache: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_kv_cache
.PHONY : test_kv_cache

# fast build rule for target.
test_kv_cache/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_kv_cache.dir/build.make CMakeFiles/test_kv_cache.dir/build
.PHONY : test_kv_cache/fast

#=============================================================================
# Target rules for targets named test_llm

# Build rule for target.
test_llm: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_llm
.PHONY : test_llm

# fast build rule for target.
test_llm/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_llm.dir/build.make CMakeFiles/test_llm.dir/build
.PHONY : test_llm/fast

#=============================================================================
# Target rules for targets named test_performance

# Build rule for target.
test_performance: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_performance
.PHONY : test_performance

# fast build rule for target.
test_performance/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_performance.dir/build.make CMakeFiles/test_performance.dir/build
.PHONY : test_performance/fast

#=============================================================================
# Target rules for targets named test_rag

# Build rule for target.
test_rag: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_rag
.PHONY : test_rag

# fast build rule for target.
test_rag/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_rag.dir/build.make CMakeFiles/test_rag.dir/build
.PHONY : test_rag/fast

#=============================================================================
# Target rules for targets named test_stt

# Build rule for target.
test_stt: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_stt
.PHONY : test_stt

# fast build rule for target.
test_stt/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_stt.dir/build.make CMakeFiles/test_stt.dir/build
.PHONY : test_stt/fast

#=============================================================================
# Target rules for targets named test_telemetry

# Build rule for target.
test_telemetry: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_telemetry
.PHONY : test_telemetry

# fast build rule for target.
test_telemetry/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_telemetry.dir/build.make CMakeFiles/test_telemetry.dir/build
.PHONY : test_telemetry/fast

#=============================================================================
# Target rules for targets named test_vlm

# Build rule for target.
test_vlm: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_vlm
.PHONY : test_vlm

# fast build rule for target.
test_vlm/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_vlm.dir/build.make CMakeFiles/test_vlm.dir/build
.PHONY : test_vlm/fast

#=============================================================================
# Target rules for targets named chat

# Build rule for target.
chat: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 chat
.PHONY : chat

# fast build rule for target.
chat/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chat.dir/build.make CMakeFiles/chat.dir/build
.PHONY : chat/fast

#=============================================================================
# Target rules for targets named asr

# Build rule for target.
asr: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 asr
.PHONY : asr

# fast build rule for target.
asr/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asr.dir/build.make CMakeFiles/asr.dir/build
.PHONY : asr/fast

asr.o: asr.cpp.o
.PHONY : asr.o

# target to build an object file
asr.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asr.dir/build.make CMakeFiles/asr.dir/asr.cpp.o
.PHONY : asr.cpp.o

asr.i: asr.cpp.i
.PHONY : asr.i

# target to preprocess a source file
asr.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asr.dir/build.make CMakeFiles/asr.dir/asr.cpp.i
.PHONY : asr.cpp.i

asr.s: asr.cpp.s
.PHONY : asr.s

# target to generate assembly for a file
asr.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asr.dir/build.make CMakeFiles/asr.dir/asr.cpp.s
.PHONY : asr.cpp.s

chat.o: chat.cpp.o
.PHONY : chat.o

# target to build an object file
chat.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chat.dir/build.make CMakeFiles/chat.dir/chat.cpp.o
.PHONY : chat.cpp.o

chat.i: chat.cpp.i
.PHONY : chat.i

# target to preprocess a source file
chat.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chat.dir/build.make CMakeFiles/chat.dir/chat.cpp.i
.PHONY : chat.cpp.i

chat.s: chat.cpp.s
.PHONY : chat.s

# target to generate assembly for a file
chat.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chat.dir/build.make CMakeFiles/chat.dir/chat.cpp.s
.PHONY : chat.cpp.s

test_curl.o: test_curl.cpp.o
.PHONY : test_curl.o

# target to build an object file
test_curl.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_curl.dir/build.make CMakeFiles/test_curl.dir/test_curl.cpp.o
.PHONY : test_curl.cpp.o

test_curl.i: test_curl.cpp.i
.PHONY : test_curl.i

# target to preprocess a source file
test_curl.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_curl.dir/build.make CMakeFiles/test_curl.dir/test_curl.cpp.i
.PHONY : test_curl.cpp.i

test_curl.s: test_curl.cpp.s
.PHONY : test_curl.s

# target to generate assembly for a file
test_curl.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_curl.dir/build.make CMakeFiles/test_curl.dir/test_curl.cpp.s
.PHONY : test_curl.cpp.s

test_embed.o: test_embed.cpp.o
.PHONY : test_embed.o

# target to build an object file
test_embed.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_embed.dir/build.make CMakeFiles/test_embed.dir/test_embed.cpp.o
.PHONY : test_embed.cpp.o

test_embed.i: test_embed.cpp.i
.PHONY : test_embed.i

# target to preprocess a source file
test_embed.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_embed.dir/build.make CMakeFiles/test_embed.dir/test_embed.cpp.i
.PHONY : test_embed.cpp.i

test_embed.s: test_embed.cpp.s
.PHONY : test_embed.s

# target to generate assembly for a file
test_embed.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_embed.dir/build.make CMakeFiles/test_embed.dir/test_embed.cpp.s
.PHONY : test_embed.cpp.s

test_graph.o: test_graph.cpp.o
.PHONY : test_graph.o

# target to build an object file
test_graph.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_graph.dir/build.make CMakeFiles/test_graph.dir/test_graph.cpp.o
.PHONY : test_graph.cpp.o

test_graph.i: test_graph.cpp.i
.PHONY : test_graph.i

# target to preprocess a source file
test_graph.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_graph.dir/build.make CMakeFiles/test_graph.dir/test_graph.cpp.i
.PHONY : test_graph.cpp.i

test_graph.s: test_graph.cpp.s
.PHONY : test_graph.s

# target to generate assembly for a file
test_graph.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_graph.dir/build.make CMakeFiles/test_graph.dir/test_graph.cpp.s
.PHONY : test_graph.cpp.s

test_index.o: test_index.cpp.o
.PHONY : test_index.o

# target to build an object file
test_index.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_index.dir/build.make CMakeFiles/test_index.dir/test_index.cpp.o
.PHONY : test_index.cpp.o

test_index.i: test_index.cpp.i
.PHONY : test_index.i

# target to preprocess a source file
test_index.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_index.dir/build.make CMakeFiles/test_index.dir/test_index.cpp.i
.PHONY : test_index.cpp.i

test_index.s: test_index.cpp.s
.PHONY : test_index.s

# target to generate assembly for a file
test_index.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_index.dir/build.make CMakeFiles/test_index.dir/test_index.cpp.s
.PHONY : test_index.cpp.s

test_kernel.o: test_kernel.cpp.o
.PHONY : test_kernel.o

# target to build an object file
test_kernel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_kernel.dir/build.make CMakeFiles/test_kernel.dir/test_kernel.cpp.o
.PHONY : test_kernel.cpp.o

test_kernel.i: test_kernel.cpp.i
.PHONY : test_kernel.i

# target to preprocess a source file
test_kernel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_kernel.dir/build.make CMakeFiles/test_kernel.dir/test_kernel.cpp.i
.PHONY : test_kernel.cpp.i

test_kernel.s: test_kernel.cpp.s
.PHONY : test_kernel.s

# target to generate assembly for a file
test_kernel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_kernel.dir/build.make CMakeFiles/test_kernel.dir/test_kernel.cpp.s
.PHONY : test_kernel.cpp.s

test_kv_cache.o: test_kv_cache.cpp.o
.PHONY : test_kv_cache.o

# target to build an object file
test_kv_cache.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_kv_cache.dir/build.make CMakeFiles/test_kv_cache.dir/test_kv_cache.cpp.o
.PHONY : test_kv_cache.cpp.o

test_kv_cache.i: test_kv_cache.cpp.i
.PHONY : test_kv_cache.i

# target to preprocess a source file
test_kv_cache.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_kv_cache.dir/build.make CMakeFiles/test_kv_cache.dir/test_kv_cache.cpp.i
.PHONY : test_kv_cache.cpp.i

test_kv_cache.s: test_kv_cache.cpp.s
.PHONY : test_kv_cache.s

# target to generate assembly for a file
test_kv_cache.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_kv_cache.dir/build.make CMakeFiles/test_kv_cache.dir/test_kv_cache.cpp.s
.PHONY : test_kv_cache.cpp.s

test_llm.o: test_llm.cpp.o
.PHONY : test_llm.o

# target to build an object file
test_llm.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_llm.dir/build.make CMakeFiles/test_llm.dir/test_llm.cpp.o
.PHONY : test_llm.cpp.o

test_llm.i: test_llm.cpp.i
.PHONY : test_llm.i

# target to preprocess a source file
test_llm.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_llm.dir/build.make CMakeFiles/test_llm.dir/test_llm.cpp.i
.PHONY : test_llm.cpp.i

test_llm.s: test_llm.cpp.s
.PHONY : test_llm.s

# target to generate assembly for a file
test_llm.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_llm.dir/build.make CMakeFiles/test_llm.dir/test_llm.cpp.s
.PHONY : test_llm.cpp.s

test_performance.o: test_performance.cpp.o
.PHONY : test_performance.o

# target to build an object file
test_performance.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_performance.dir/build.make CMakeFiles/test_performance.dir/test_performance.cpp.o
.PHONY : test_performance.cpp.o

test_performance.i: test_performance.cpp.i
.PHONY : test_performance.i

# target to preprocess a source file
test_performance.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_performance.dir/build.make CMakeFiles/test_performance.dir/test_performance.cpp.i
.PHONY : test_performance.cpp.i

test_performance.s: test_performance.cpp.s
.PHONY : test_performance.s

# target to generate assembly for a file
test_performance.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_performance.dir/build.make CMakeFiles/test_performance.dir/test_performance.cpp.s
.PHONY : test_performance.cpp.s

test_rag.o: test_rag.cpp.o
.PHONY : test_rag.o

# target to build an object file
test_rag.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_rag.dir/build.make CMakeFiles/test_rag.dir/test_rag.cpp.o
.PHONY : test_rag.cpp.o

test_rag.i: test_rag.cpp.i
.PHONY : test_rag.i

# target to preprocess a source file
test_rag.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_rag.dir/build.make CMakeFiles/test_rag.dir/test_rag.cpp.i
.PHONY : test_rag.cpp.i

test_rag.s: test_rag.cpp.s
.PHONY : test_rag.s

# target to generate assembly for a file
test_rag.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_rag.dir/build.make CMakeFiles/test_rag.dir/test_rag.cpp.s
.PHONY : test_rag.cpp.s

test_stt.o: test_stt.cpp.o
.PHONY : test_stt.o

# target to build an object file
test_stt.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_stt.dir/build.make CMakeFiles/test_stt.dir/test_stt.cpp.o
.PHONY : test_stt.cpp.o

test_stt.i: test_stt.cpp.i
.PHONY : test_stt.i

# target to preprocess a source file
test_stt.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_stt.dir/build.make CMakeFiles/test_stt.dir/test_stt.cpp.i
.PHONY : test_stt.cpp.i

test_stt.s: test_stt.cpp.s
.PHONY : test_stt.s

# target to generate assembly for a file
test_stt.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_stt.dir/build.make CMakeFiles/test_stt.dir/test_stt.cpp.s
.PHONY : test_stt.cpp.s

test_telemetry.o: test_telemetry.cpp.o
.PHONY : test_telemetry.o

# target to build an object file
test_telemetry.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_telemetry.dir/build.make CMakeFiles/test_telemetry.dir/test_telemetry.cpp.o
.PHONY : test_telemetry.cpp.o

test_telemetry.i: test_telemetry.cpp.i
.PHONY : test_telemetry.i

# target to preprocess a source file
test_telemetry.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_telemetry.dir/build.make CMakeFiles/test_telemetry.dir/test_telemetry.cpp.i
.PHONY : test_telemetry.cpp.i

test_telemetry.s: test_telemetry.cpp.s
.PHONY : test_telemetry.s

# target to generate assembly for a file
test_telemetry.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_telemetry.dir/build.make CMakeFiles/test_telemetry.dir/test_telemetry.cpp.s
.PHONY : test_telemetry.cpp.s

test_utils.o: test_utils.cpp.o
.PHONY : test_utils.o

# target to build an object file
test_utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_curl.dir/build.make CMakeFiles/test_curl.dir/test_utils.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_embed.dir/build.make CMakeFiles/test_embed.dir/test_utils.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_graph.dir/build.make CMakeFiles/test_graph.dir/test_utils.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_index.dir/build.make CMakeFiles/test_index.dir/test_utils.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_kernel.dir/build.make CMakeFiles/test_kernel.dir/test_utils.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_kv_cache.dir/build.make CMakeFiles/test_kv_cache.dir/test_utils.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_llm.dir/build.make CMakeFiles/test_llm.dir/test_utils.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_performance.dir/build.make CMakeFiles/test_performance.dir/test_utils.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_rag.dir/build.make CMakeFiles/test_rag.dir/test_utils.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_stt.dir/build.make CMakeFiles/test_stt.dir/test_utils.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_telemetry.dir/build.make CMakeFiles/test_telemetry.dir/test_utils.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_vlm.dir/build.make CMakeFiles/test_vlm.dir/test_utils.cpp.o
.PHONY : test_utils.cpp.o

test_utils.i: test_utils.cpp.i
.PHONY : test_utils.i

# target to preprocess a source file
test_utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_curl.dir/build.make CMakeFiles/test_curl.dir/test_utils.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_embed.dir/build.make CMakeFiles/test_embed.dir/test_utils.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_graph.dir/build.make CMakeFiles/test_graph.dir/test_utils.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_index.dir/build.make CMakeFiles/test_index.dir/test_utils.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_kernel.dir/build.make CMakeFiles/test_kernel.dir/test_utils.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_kv_cache.dir/build.make CMakeFiles/test_kv_cache.dir/test_utils.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_llm.dir/build.make CMakeFiles/test_llm.dir/test_utils.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_performance.dir/build.make CMakeFiles/test_performance.dir/test_utils.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_rag.dir/build.make CMakeFiles/test_rag.dir/test_utils.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_stt.dir/build.make CMakeFiles/test_stt.dir/test_utils.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_telemetry.dir/build.make CMakeFiles/test_telemetry.dir/test_utils.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_vlm.dir/build.make CMakeFiles/test_vlm.dir/test_utils.cpp.i
.PHONY : test_utils.cpp.i

test_utils.s: test_utils.cpp.s
.PHONY : test_utils.s

# target to generate assembly for a file
test_utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_curl.dir/build.make CMakeFiles/test_curl.dir/test_utils.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_embed.dir/build.make CMakeFiles/test_embed.dir/test_utils.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_graph.dir/build.make CMakeFiles/test_graph.dir/test_utils.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_index.dir/build.make CMakeFiles/test_index.dir/test_utils.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_kernel.dir/build.make CMakeFiles/test_kernel.dir/test_utils.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_kv_cache.dir/build.make CMakeFiles/test_kv_cache.dir/test_utils.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_llm.dir/build.make CMakeFiles/test_llm.dir/test_utils.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_performance.dir/build.make CMakeFiles/test_performance.dir/test_utils.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_rag.dir/build.make CMakeFiles/test_rag.dir/test_utils.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_stt.dir/build.make CMakeFiles/test_stt.dir/test_utils.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_telemetry.dir/build.make CMakeFiles/test_telemetry.dir/test_utils.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_vlm.dir/build.make CMakeFiles/test_vlm.dir/test_utils.cpp.s
.PHONY : test_utils.cpp.s

test_vlm.o: test_vlm.cpp.o
.PHONY : test_vlm.o

# target to build an object file
test_vlm.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_vlm.dir/build.make CMakeFiles/test_vlm.dir/test_vlm.cpp.o
.PHONY : test_vlm.cpp.o

test_vlm.i: test_vlm.cpp.i
.PHONY : test_vlm.i

# target to preprocess a source file
test_vlm.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_vlm.dir/build.make CMakeFiles/test_vlm.dir/test_vlm.cpp.i
.PHONY : test_vlm.cpp.i

test_vlm.s: test_vlm.cpp.s
.PHONY : test_vlm.s

# target to generate assembly for a file
test_vlm.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_vlm.dir/build.make CMakeFiles/test_vlm.dir/test_vlm.cpp.s
.PHONY : test_vlm.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... asr"
	@echo "... chat"
	@echo "... test_curl"
	@echo "... test_embed"
	@echo "... test_graph"
	@echo "... test_index"
	@echo "... test_kernel"
	@echo "... test_kv_cache"
	@echo "... test_llm"
	@echo "... test_performance"
	@echo "... test_rag"
	@echo "... test_stt"
	@echo "... test_telemetry"
	@echo "... test_vlm"
	@echo "... asr.o"
	@echo "... asr.i"
	@echo "... asr.s"
	@echo "... chat.o"
	@echo "... chat.i"
	@echo "... chat.s"
	@echo "... test_curl.o"
	@echo "... test_curl.i"
	@echo "... test_curl.s"
	@echo "... test_embed.o"
	@echo "... test_embed.i"
	@echo "... test_embed.s"
	@echo "... test_graph.o"
	@echo "... test_graph.i"
	@echo "... test_graph.s"
	@echo "... test_index.o"
	@echo "... test_index.i"
	@echo "... test_index.s"
	@echo "... test_kernel.o"
	@echo "... test_kernel.i"
	@echo "... test_kernel.s"
	@echo "... test_kv_cache.o"
	@echo "... test_kv_cache.i"
	@echo "... test_kv_cache.s"
	@echo "... test_llm.o"
	@echo "... test_llm.i"
	@echo "... test_llm.s"
	@echo "... test_performance.o"
	@echo "... test_performance.i"
	@echo "... test_performance.s"
	@echo "... test_rag.o"
	@echo "... test_rag.i"
	@echo "... test_rag.s"
	@echo "... test_stt.o"
	@echo "... test_stt.i"
	@echo "... test_stt.s"
	@echo "... test_telemetry.o"
	@echo "... test_telemetry.i"
	@echo "... test_telemetry.s"
	@echo "... test_utils.o"
	@echo "... test_utils.i"
	@echo "... test_utils.s"
	@echo "... test_vlm.o"
	@echo "... test_vlm.i"
	@echo "... test_vlm.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

